import os

SNAPSHOTS_PATH = "/snapshots"
BN_ARANGO_PROTOCOL = os.environ['BN_ARANGO_PROTOCOL']
BN_ARANGO_HOST= os.environ['BN_ARANGO_HOST']
BN_ARANGO_PORT = os.environ['BN_ARANGO_PORT']
ARANGO_SERVER = BN_ARANGO_PROTOCOL + '://' + BN_ARANGO_HOST + ':' + BN_ARANGO_PORT
