import os
import hashlib
from eth_keys import keys
from eth_utils import decode_hex

NETWORK = os.environ["BN_CONSENSUS_NETWORK"]
TOPIC_ID = os.environ["BN_CONSENSUS_TOPIC_ID"]

OPERATOR_ID = os.environ["BN_CONSENSUS_OPERATOR_ID"]
OPERATOR_KEY = os.environ["BN_CONSENSUS_OPERATOR_KEY"]
MIRROR_NODE_URL = os.environ["BN_CONSENSUS_MIRROR_NODE_URL"]

MAX_DATA_SIZE = int(os.environ["BN_CONSENSUS_MAX_DATA_SIZE"])

SNAPSHOTS_PERIOD = int(os.environ["BN_CONSENSUS_SNAPSHOTS_PERIOD"])
SNAPSHOTS_PATH = "/snapshots/dump_{}"

BN_ARANGO_PROTOCOL = os.environ["BN_ARANGO_PROTOCOL"]
BN_ARANGO_HOST = os.environ["BN_ARANGO_HOST"]
BN_ARANGO_PORT = int(os.environ["BN_ARANGO_PORT"])
ARANGO_SERVER = f"{BN_ARANGO_PROTOCOL}://{BN_ARANGO_HOST}:{BN_ARANGO_PORT}"

APPLY_URL = ARANGO_SERVER + os.environ["BN_CONSENSUS_APPLY_URL"]
DUMP_URL = ARANGO_SERVER + os.environ["BN_CONSENSUS_DUMP_URL"]
